# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049abf293be14fa921ac329c3867b57e3694a5d0dd796f9d1140246d885d75792bb05d7f378b075c087b5c1a04f922cab8485251c90b4bb15bb149ddcee1e2e0

test:
  secret_key_base: 7ad910850e7356083413634ae46a0eb579871b85adff0e23601d13bca327175c191cfd2431f737fef044a005a73fee75edb07780e2d9480e8fe3dc80b82852c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
